### ISSUE TITLE
Can't install because debian check

### ISSUE THREAD

**Issue by vendelieu** [zzzkeil/base_setups#1]
https://github.com/zzzkeil/base_setups/blob/6863341db027b1498baad4577d9d30e314c903f0/base_setup.sh#L26

Installation on ubuntu can't process

**Comment by vendelieu** [comment]
for some reason this line breaks installation on my linux :(

**Comment by zzzkeil** [comment]
Ok,
plz, post your output from this command 
lsb_release -a

my example :
```
comegetsome@vpn02server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
